server:
  port: 9505

spring:
  application:
    # 应用名称
    name: share-stastics
  profiles:
    # 环境配置
    active: dev
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        # 服务注册地址
        server-addr: 47.119.113.9:8848
        namespace:  18bcfec9-e0bc-45e2-a7fa-4d79d8fbef9f
#  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: deepseek-r1:1.5b
#          temperature: 0.7
